fullnameOverride: ui

image:
  repository: public.ecr.aws/aws-containers/retail-store-sample-ui
  tag: ""

app:
  endpoints:
    catalog: http://catalog:80
    carts: http://carts:80
    checkout: http://checkout:80
    orders: http://orders:80
