fullnameOverride: checkout
image:
  repository: 341796273495.dkr.ecr.ap-southeast-1.amazonaws.com/e-comm/checkout
  tag: "f62ebab08201e4be4b91511b64ce46850a159e41-amd64"
app:
  persistence:
    provider: redis
  endpoints:
    orders: http://orders:80
redis:
  create: true
