fullnameOverride: orders
image:
  repository: 341796273495.dkr.ecr.ap-southeast-1.amazonaws.com/e-comm/orders
  tag: "f62ebab08201e4be4b91511b64ce46850a159e41-amd64"
app:
  persistence:
    provider: postgres
    secret:
      password: OrdersPassword2026
  messaging:
    provider: rabbitmq
postgresql:
  create: true
rabbitmq:
  create: true
