fullnameOverride: orders
image:
  repository: public.ecr.aws/aws-containers/retail-store-sample-orders
  tag: "f62ebab08201e4be4b91511b64ce46850a159e41"
app:
  persistence:
    provider: postgres
  messaging:
    provider: rabbitmq
postgresql:
  create: true
rabbitmq:
  create: true
