fullnameOverride: carts
image:
  repository: public.ecr.aws/aws-containers/retail-store-sample-cart
  tag: "f62ebab08201e4be4b91511b64ce46850a159e41"
app:
  persistence:
    provider: dynamodb
dynamodb:
  create: true
